# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PCybernetics' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PCybernetics
  pod 'Eureka'
  pod 'ImageRow', '~> 3.0'
  pod 'ColorPickerRow', :git => 'https://github.com/EurekaCommunity/ColorPickerRow'
  pod 'UIColor_Hex_Swift'
  pod 'SwiftMailgun'

end
